name: newbug
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: 0.20.2
  get: 4.7.2
  #go_router: 16.2.1
  dio: 5.9.0
  pretty_dio_logger: 1.4.0
  logger: 2.6.1
  auto_size_text: 3.0.0
  shared_preferences: 2.5.3
  cached_network_image: 3.4.1
  flutter_screenutil: 5.9.3
  pull_to_refresh: 2.0.0
  flutter_easyloading: 3.0.5
  permission_handler: 12.0.1
  event_bus: ^2.0.1
  url_launcher: 6.3.2
  #资源选择器
  image_picker: 1.2.0
  path_provider: 2.1.5
  webview_flutter: 4.13.0
  wechat_assets_picker: 9.8.0
  wechat_camera_picker: 4.4.0
  flutter_image_compress: 2.4.0
  #keyboard_visibility
  keyboard_visibility_pro: 1.0.0
  email_validator: 3.0.0
  #选择时间
  awesome_datetime_picker: ^0.1.1
  #flutter_intro: 3.4.0
  #custom_pop_up_menu: ^1.2.4
  #overlay_popup_dialog: ^2.0.2
  flutter_popup: ^3.3.9
  flutter_swiper_null_safety_flutter3: ^4.0.3
  flutter_slidable: 4.0.3
  # pinput: ^5.0.2
  #extended_text: 15.0.2
  #bot_toast: ^4.1.3
  overlay_support: 2.1.0
  #是否使用VPN
  #nexever_check_plugin: 0.6.0
  #vpn_connection_detector: ^1.0.10
  #是否使用代理
  #native_flutter_proxy: ^0.2.3
  bubble_pop_up: ^2.1.0
  bubble_box: 0.5.3
 # bubble_tab_indicator: ^0.1.6
  timer_count_down: ^2.2.2
  #扩展图片（缩放，平移）
  extended_image: 10.0.1
  #photo_view: ^0.15.0
  #获取视频第一帧
  #video_thumbnail: 0.5.6
  flutter_video_thumbnail_plus: ^1.0.5
  video_player: 2.10.0
  #视频进度
  #audio_video_progress_bar: 2.0.3
  native_dio_adapter: 1.5.0
  device_info_plus: 12.1.0
  package_info_plus: 9.0.0
  crypto: 3.0.6
  time_zone_plus: 0.0.4
  adjust_sdk: 5.4.4
  encrypt: 5.0.3
  #platform_device_id_plus: ^1.0.7
  mobile_device_identifier: ^0.0.3
  #钥匙串
  flutter_secure_storage: 9.2.4
  #flutter_cache_manager: 3.4.1
  http: 1.5.0
  video_compress: 3.1.4
  collection: 1.19.1








  better_player:
    path: plugins/betterplayer



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/decoration/
    - assets/status/
    - assets/avatar/
    - assets/subscribe/

  fonts:
    - family: font1
      fonts:
        - asset: font/Pattaya-Regular-TTF.ttf
    - family: font2
      fonts:
        - asset: font/Pattaya-Regular-OTF.otf